import { Company, Manager } from '@/types/contract';

export const COMPANIES: Company[] = [
  {
    id: 'logitrans_uz',
    nameRu: 'ИП ООО «LOGITRANS UZBEKISTAN»',
    nameEn: 'IP OOO «LOGITRANS UZBEKISTAN»',
    city: 'Tashkent',
    cityRu: 'г. Ташкент',
    country: 'Uzbekistan',
    countryRu: 'Республика Узбекистан',
    address: 'Tashkent city, Mirzoulugbek district, st. Kori Niyoziy 11 building, 1 block, 4 floor, № 26',
    addressRu: 'г. Ташкент, Мирзоулугбекский район, Ул. Кори Ниёзий 11 дом, 1 блок, 4 этаж, 26 офис',
    director: 'Осман Демир',
    bin: '305657870',
    bank: 'AO «Ziraat Bank Uzbekistan»',
    bankRu: 'АО «Ziraat Bank Uzbekistan»',
    accountUSD: '20208840100901348003 (USD)',
    accountEUR: '20208978100901348001 (EUR)',
    accountLocal: '20208000500901348001 (UZS)',
    swift: 'TCZBUZ22',
    phone: '+99897 444-30-74, +99897 444-30-71',
    email: 'infouz@logitransport.com',
    kbe: 'ОКЕД(КБЕ) 49410',
    extraBankInfo: 'МФО (Код Филиал)- 00395',
    legalCode: 'ИНН: 305657870',
    currency: 'USD',
    signatory: 'Osman Demir',
  },
  {
    id: 'logitrans_kz',
    nameRu: 'ТОО «LOGITRANS LOJISTIK GROUP» (ЛОГИТРАНС ЛОЖИСТИК ГРОУП)',
    nameEn: 'TOO «Logitrans Lojistik Group»',
    city: 'Almaty',
    cityRu: 'г. Алматы',
    country: 'Kazakhstan',
    countryRu: 'Республика Казахстан',
    address: 'Republic of Kazakhstan, 050012, Almaty, pr. Seifullin, 498, room 109, office 312',
    addressRu: 'Республика Казахстан, 050012, г. Алматы, пр. Сейфуллина, д. 498 пом. 109, кв. (офис) 312',
    director: 'Рамазан Кая',
    bin: '101140013870',
    bank: 'АО «Банк ЦентрКредит»',
    bankRu: 'АО «Банк ЦентрКредит»',
    accountUSD: 'KZ778562203215879946 (USD)',
    accountEUR: 'KZ118562203215879970 (EUR)',
    accountLocal: 'KZ888562203115879926 (KZT)',
    swift: 'KCJBKZKXXXX',
    phone: '',
    email: '',
    kbe: 'КБЕ 17',
    extraBankInfo: 'Адрес банка: 050000, КАЗАХСТАН, АЛМАТЫ 2, АЛМАЛИНСКИЙ р-н, БОГЕНБАЙ БАТЫРА ул, дом 156',
    legalCode: 'БИН (ИНН): 101140013870',
    currency: 'USD',
    signatory: 'Ramazan Kaya',
  },
  {
    id: 'lgs_kz',
    nameRu: 'ТОО «LGS GLOBAL SERVIS» (ЭЛ ДЖИ ЭС ГЛОБАЛ СЕРВИС)',
    nameEn: 'TOO «LGS GLOBAL SERVIS»',
    city: 'Almaty',
    cityRu: 'г. Алматы',
    country: 'Kazakhstan',
    countryRu: 'Республика Казахстан',
    address: 'Almaty, pr. Seifullin, office 58',
    addressRu: 'г.Алматы, пр. Сейфуллина, пом 58',
    director: 'К. Рамазан',
    bin: '120240012536',
    bank: 'АО ДБ СБЕРБАНК',
    bankRu: 'АО ДБ СБЕРБАНК',
    accountUSD: 'KZ80914002203US00268 (USD)',
    accountEUR: '',
    accountLocal: '',
    swift: 'SABRKZKA',
    phone: '+7 701 081 7208',
    email: '',
    kbe: 'КБЕ 17',
    extraBankInfo: 'Кореспондент Банк: Moscow, Russia, SWIFT: SABRRUMM',
    legalCode: 'БИН(ИНН): 120240012536',
    currency: 'USD',
    signatory: 'K. Ramazan',
  },
  {
    id: 'lgs_ru',
    nameRu: 'ООО «ЛГС»',
    nameEn: 'OOO «LGS»',
    city: 'Moscow',
    cityRu: 'г. Москва',
    country: 'Russia',
    countryRu: 'Российская Федерация',
    address: '121354, Moscow, ul. Dorogobugskaya, 14, bld.1, room 4, floor 1',
    addressRu: '121354, г. Москва, ул. Дорогобужская, дом № 14, стр. 1, пом.4, эт. 1',
    director: 'Устюнел Йалчын',
    bin: '7731351913',
    bank: 'ООО ПроКоммерцБанк',
    bankRu: 'ООО ПроКоммерцБанк',
    accountUSD: '40702840802021002255 (USD)',
    accountEUR: '',
    accountLocal: '',
    swift: 'PROKRUMM',
    phone: '+7(495) 645 68 12',
    email: '',
    kbe: 'КПП 773101001',
    extraBankInfo: 'банк-посредник: AVTBRUMMXXX - SWIFT Code - URALSIB BANK MOSCOW',
    legalCode: 'ИНН 7731351913',
    currency: 'USD',
    signatory: 'Üstünel Yalçın',
  },
  {
    id: 'logitrans_tr',
    nameRu: 'Logitrans Lojistik A.Ş.',
    nameEn: 'Logitrans Lojistik A.Ş.',
    city: 'Istanbul',
    cityRu: 'г. Стамбул',
    country: 'Turkey',
    countryRu: 'Турецкая Республика',
    address: 'Orhanlı mahallesi Derviş caddesi No 24 Kat 1 D.4B Tuzla - İstanbul',
    addressRu: 'Ул. Дервиш, д. 24, эт. 1, кв. 4B, Тузла - Стамбул',
    director: 'Джихан Сюнел',
    bin: '1616',
    bank: 'Garanti Bankasi',
    bankRu: 'Garanti Bankasi',
    accountUSD: 'IBAN: TR80 0006 2001 6160 0009 0904 80 (USD)',
    accountEUR: '',
    accountLocal: '',
    swift: 'TGBATRIS',
    phone: '',
    email: '',
    kbe: '',
    extraBankInfo: 'İMES TİCARİ KOD: 1616, Account: 9090480',
    legalCode: 'TIN: 1616',
    currency: 'USD',
    signatory: 'Cihan Sünel',
  },
];

export const MANAGERS: Manager[] = [
  { id: 'mgr1', name: 'Ramzan Kaya', companyId: 'logitrans_kz' },
  { id: 'mgr2', name: 'Osman Demir', companyId: 'logitrans_uz' },
  { id: 'mgr3', name: 'Üstünel Yalçın', companyId: 'lgs_ru' },
  { id: 'mgr4', name: 'Cihan Sünel', companyId: 'logitrans_tr' },
  { id: 'mgr5', name: 'Менеджер 1', companyId: 'lgs_kz' },
  { id: 'mgr6', name: 'Менеджер 2', companyId: 'logitrans_uz' },
];

export const CURRENCIES = ['USD', 'EUR', 'RUB', 'KZT', 'UZS', 'TRY'];
